/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.awt.Toolkit;

import java.awt.event.WindowEvent;
import java.sql.ResultSet;

import javax.swing.JFrame;


import javax.swing.JOptionPane;


import java.sql.*;
import javax.swing.*;

/**
 *
 * @author Ben
 */
public class Login_Registrationpage extends javax.swing.JFrame {
Connection connect = null;
PreparedStatement pst = null;
ResultSet rs =null;


private JFrame frame;


    /**
     * Creates new form Login_Registrationpage
     */
    
    
    private void systemExit(){
            WindowEvent winCloseing = new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
        }

    public Login_Registrationpage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl1Username = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lb1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        UsernameField = new javax.swing.JTextField();
        PasswordField = new javax.swing.JPasswordField();
        btn1Login = new javax.swing.JButton();
        btn2Clear = new javax.swing.JButton();
        btn3Close = new javax.swing.JButton();
        LBL1 = new javax.swing.JLabel();

        lbl1Username.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbl1Username.setText("Username:");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximizedBounds(new java.awt.Rectangle(1380, 800, 800, 800));
        setMaximumSize(new java.awt.Dimension(1380, 800));
        setPreferredSize(new java.awt.Dimension(1380, 800));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 12));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lb1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lb1.setText("Username:");
        jPanel1.add(lb1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setText("Password:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, -1, -1));

        UsernameField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        UsernameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsernameFieldActionPerformed(evt);
            }
        });
        jPanel1.add(UsernameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 210, 196, -1));

        PasswordField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        jPanel1.add(PasswordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 300, 196, -1));

        btn1Login.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn1Login.setText("Login");
        btn1Login.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        btn1Login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1LoginActionPerformed(evt);
            }
        });
        jPanel1.add(btn1Login, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 250, 63, -1));

        btn2Clear.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn2Clear.setText("Clear");
        btn2Clear.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        btn2Clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ClearActionPerformed(evt);
            }
        });
        jPanel1.add(btn2Clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 250, 63, -1));

        btn3Close.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn3Close.setText("Close");
        btn3Close.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        btn3Close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3CloseActionPerformed(evt);
            }
        });
        jPanel1.add(btn3Close, new org.netbeans.lib.awtextra.AbsoluteConstraints(814, 106, 62, -1));

        LBL1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        LBL1.setText("Music Social Network - Login");
        jPanel1.add(LBL1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, 970, 39));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 160, 810, 500));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn3CloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3CloseActionPerformed
       System.exit(0);
    }//GEN-LAST:event_btn3CloseActionPerformed

    private void btn2ClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ClearActionPerformed
       UsernameField.setText(null);
       PasswordField.setText(null);
    }//GEN-LAST:event_btn2ClearActionPerformed

    private void btn1LoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1LoginActionPerformed
       connect = MysqlConnect.ConnectDB();
       String Sql = "Select * from login where username=? and password=?";
       try{
           pst=connect.prepareStatement(Sql);
           pst.setString(1, UsernameField.getText());
           pst.setString(2, PasswordField.getText());
           rs=pst.executeQuery();
           if(rs.next()){
               JOptionPane.showMessageDialog(null, "Welcome User");
               welcome w=new welcome();
               w.setVisible(true);
           }
           else{
               JOptionPane.showMessageDialog(null, "Invalid Username or password", "Access Denied", JOptionPane.ERROR_MESSAGE);
               
           }
      }catch(Exception e){
          JOptionPane.showMessageDialog(null, e);
      }
       
    }//GEN-LAST:event_btn1LoginActionPerformed

    private void CloseMe(){
        WindowEvent meClose = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(meClose);
    }
    
    private void UsernameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsernameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UsernameFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login_Registrationpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login_Registrationpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login_Registrationpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login_Registrationpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login_Registrationpage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LBL1;
    private javax.swing.JPasswordField PasswordField;
    private javax.swing.JTextField UsernameField;
    private javax.swing.JButton btn1Login;
    private javax.swing.JButton btn2Clear;
    private javax.swing.JButton btn3Close;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lb1;
    private javax.swing.JLabel lbl1Username;
    // End of variables declaration//GEN-END:variables
}


